Add support for fixed compilation database (compile_flags.txt)
apple/sourcekit-lsp pull request #375
Opened 2021-03-13 16:25 UTC by hashemi

This small change adds support for fixed compilation database (compile_flags.txt), ideal for simple codebases that do not use CMake with an auto-generated compile_commands.json file.

See clangd's (compilation database documentation)[https://clang.llvm.org/docs/JSONCompilationDatabase.html] under Alternatives.

@benlangmuir

2021-03-13 17:56 UTC, benlangmuir requested changes
@swift-ci please test

2021-03-13 17:56 UTC, benlangmuir commented on Sources/SKCore/CompilationDatabase.swift
> +    [Command(directory: "", filename: path.path, commandLine: fixedArgs + [path.path])]
We should make Command.directory optional and use `nil` here.

Edit: actually, should we instead store the directory from the path we use when constructing the FixedCompilationDatabase (i.e. the directory that contains compile_commands.txt)?

2021-03-13 17:56 UTC, benlangmuir commented on Tests/SKCoreTests/CompilationDatabaseTests.swift
> +  func testFixedCompilationDatabase() {
Please regenerate Linux tests

```
swift build --regenerate-linuxmain
```

If your version of swiftpm is too new and no longer supports that you can add the new test manually to `Tests/SKCoreTests/XCTestManifests.swift`

2021-03-13 17:56 UTC, benlangmuir commented
This looks great, just a couple of minor comments.  Thanks!

2021-03-13 18:39 UTC, hashemi commented
Thanks for the review Ben! Made the changes.

2021-03-15 16:26 UTC, benlangmuir commented
@swift-ci please test

2021-03-15 18:01 UTC, merged

2021-03-15 18:01 UTC, benlangmuir commented
Thanks!